### ISSUE TITLE
Canary: Toolbar styles

### ISSUE THREAD

**Issue by s10wen** [s10wen/SO-Dark-Monokai-v3#23]
![screen shot 2013-10-23 at 17 17 59](https://f.cloud.github.com/assets/1136114/1391570/c2f2a184-3bfe-11e3-99ce-7d74ee6a1360.png)

**Comment by RaphaelDDL** [comment]
I gave a shot onto fixing that:

![image](https://f.cloud.github.com/assets/1087109/1485846/b101d554-471a-11e3-9526-6d4a6471252d.png)

Got a little narrower than yours but I liked that way, with 30px height and active state with same color of element's background. And I left the close button, I miss it :P

That also affected the tabs on network:
![image](https://f.cloud.github.com/assets/1087109/1485930/b19b6010-471b-11e3-8e6b-a364769871bf.png)
There, had to be the opposite: dark bg on all, lighter on the active.

Also tried Improve the upper bar of Network since icons were almost invisible (yes, that gray is lighter than the normal ones, but I didn't feel was too weird to be lighter).

![image](https://f.cloud.github.com/assets/1087109/1485856/c76cef68-471a-11e3-8419-7bde08c8d8e7.png)
(applies to timeline too)
![image](https://f.cloud.github.com/assets/1087109/1485906/7c69ed8a-471b-11e3-8d18-bf64fba617ea.png)

Also I tried to change the settings:

![image](https://f.cloud.github.com/assets/1087109/1485872/f51fc2b4-471a-11e3-89c0-61c22a252f82.png)
Just failed hard trying to overwrite the active tab, which don't apply even with important, dunno why.

Let me know if that's okay. I'll try separate the modified CSS since I did it on an older version of your canary css.

**Comment by s10wen** [comment]
Nice work! Looking good. If you fork my repo and commit your changes there then I can have a better look.
