### ISSUE TITLE
Vertical position, cssbar is not visible

### ISSUE THREAD

**Issue by nelsera** [s10wen/SO-Dark-Monokai-v3#28]
![screenshot](https://f.cloud.github.com/assets/6188074/1989171/73ed6886-8473-11e3-9cea-6c876113c3ca.jpg)

**Comment by s10wen** [comment]
I'm looking to move this theme over to:
https://github.com/s10wen/SO-Dark-Monokai-v3/issues/27

It's still a wip but it's getting there and I think going forward it's a better solution.

So I'd recommend checking that repo out and changing the theme partial include over and if the issue is still there if you could set an issue over there I'll get around to it.

Cheers.
