### ISSUE TITLE
Manual instal is not working

### ISSUE THREAD

**Issue by PaoloFalomo** [s10wen/SO-Dark-Monokai-v3#33]
I think since last chrome update the `Custom.css` file is no longer available. The folder doesn't even exists

**Comment by s10wen** [comment]
This issue is mentioned in the `README.md`:
https://github.com/s10wen/SO-Dark-Monokai-v3

I no longer support this repo, I'd recommend checking out:
https://github.com/mauricecruz/zero-base-themes/blob/master/themes/s10wen-monokai.less
https://github.com/mauricecruz/chrome-devtools-zerodarkmatrix-theme

Hope that helps :)
